---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/robertdebock/pre-commit
    rev: v1.4.5
    hooks:
      - id: ansible_role_find_empty_directories
      - id: ansible_role_find_empty_files
      - id: ansible_role_find_undefined_handlers
      - id: ansible_role_find_unquoted_values
      - id: ansible_role_find_unused_variable
      - id: ansible_role_fix_readability

  - repo: https://github.com/ansible-community/ansible-lint
    rev: v5.3.2
    hooks:
      - id: ansible-lint
